Travlendar/config/routes.rb
Rails.application.routes.draw do

	resources :user
	resources :meeting
	resources :notification, only: [:index]
	resources :default_location


	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get '/' => 'homepage#index', as: 'homepage'
	post '/' => 'homepage#post_index', as: 'root_post'
	post '/user/new', to: 'user#create'
	delete '/logout', to: 'homepage#destroy'

	# User
	get 'user/new'
	post 'user/:id/edit', to: 'user#post_edit'
	get 'user/search/:id' => 'user#search', as: 'search_user'
	get 'user/search_contacts/:id' => 'user#search_contacts', as: 'search_user_contact'
	get 'user/contacts/:id' => 'user#contacts', as: 'contacts_page'
	get 'user/remove_from_contacts/:user_id/:to_delete_id' => 'user#delete_contact', as: 'delete_contact'
	get 'user/add_to_contacts/:user_id/:to_add_id' => 'user#add_contact', as: 'add_contact'
	get 'user/:id/settings' => 'user#settings', as: 'settings_page'
	patch 'user/:id/settings/change_preference_list' => 'user#change_preference_list', as: 'change_preference_list'
	get 'user/:id/add_constraint' => 'user#add_constraint', as: 'add_constraint'
	post 'user/:id/add_constraint', to: 'user#create_constraint'
	get 'user/delete_constraint/:user_id/:constraint_id' => 'user#delate_constraint', as: 'delete_constraint'
	get 'user/delete_email/:user_id/:email_id' => 'user#delete_email', as: 'delete_email'
	get 'user/delete_social/:user_id/:social_user_id' => 'user#delete_social', as: 'delete_social'

	# Meeting
	get 'meeting/:id/participants_page' => 'meeting#participants_page', as: 'participants_page'
	get 'meeting/remove_participant/:meeting_id/:user_id' => 'meeting#remove_from_meeting', as: 'remove_from_meeting'
	get 'meeting/nominate_admin/:meeting_id/:user_id' => 'meeting#nominate_admin', as: 'nominate_admin'
	post '/meeting/new', to: 'meeting#create'
	get 'meeting/accept_participation/:meeting_id/:user_id' => 'meeting#accept', as: 'accept_meeting'
	get 'meeting/decline_participation/:meeting_id/:user_id' => 'meeting#decline', as: 'decline_meeting'

	# Calendar Page
	get 'calendar/day/:year/:month/:day' => 'calendar#show_day', constraints: {year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/}, as: 'calendar_day', defaults: {year: DateTime.now.year, month: DateTime.now.month, day: DateTime.now.day}
	get 'calendar/week/:year/:week' => 'calendar#show_week', constraints: {year: /\d{4}/, week: /\d{1,2}/}, as: 'calendar_week'
	get 'calendar/month/:year/:month' => 'calendar#show_month', constraints: {year: /\d{4}/, month: /\d{1,2}/}, as: 'calendar_month'

	# Travel
	get 'travel/:id' => 'travel#show', as: 'show_travel'

	# Notification
	get 'notification/resolve_warning/:meeting_participation_id' => 'notification#resolve_warning', as: 'resolve_warning'

	# Default Location
	post 'default_location/new', to: 'default_location#create'
	get 'default_location/delete_dl/:default_location_id/:user_id' => 'default_location#delete', as: 'delete_default_location'
	get 'default_location/first_def_location/:user_id' => 'default_location#first_def_location', as: 'create_first_def_location'
	post 'default_location/first_def_location/:user_id', to: 'default_location#first_creation'

	# Break
	get 'break/:id/add_break' => 'break#add_break', as: 'add_break'
	post 'break/:id/add_break', to: 'break#create_break'
	get 'user/delete_break/:user_id/:break_id' => 'break#delete_break', as: 'delete_break'
end

Travlendar/app/models/meeting.rb
# This class manages the model(relations, validations and base methods) of the Meeting object
class Meeting < ApplicationRecord
	belongs_to :location
	has_many :meeting_participations
	has_many :users, through: :meeting_participations

	validates :start_date, :end_date, :title, presence: true

	validate :date_consistency

	# This method retrieve all the participants of a meeting
	def get_participants(response_status_number)
		meeting_participations.where(response_status: response_status_number)
	end

	# This method retrieve all the meeting participations linked with the current meeting
	def get_meeting_participaton(user_to_search)
		meeting_participations.find_by(user_id: user_to_search.id)
	end

	private

	# This method check if the dates are consistent
	def date_consistency
		return if [start_date.blank?, end_date.blank?].any?
		errors.add(:end_date, 'must be after start_date') if start_date > end_date
	end
end

Travlendar/app/helpers/meeting_helper.rb
# This is a helper module containing functions to be called to update the scheduling of meeting participations
module MeetingHelper

	# This function has to be called to create both a meeting and a meeting_participation and store them on the db.
	#
	# In practice, use this only for the user that creates a meeting and not for the invited users
	#
	# * start_date and end_date must be valid DateTime objects
	# * title must be a non-empty string
	# * location must be a Location already saved in the db
	# * user must be a User
	#
	# returns a hash containing the meeting (nil in case of errors), the meeting_participation (nil in case of errors)
	# and a status flag (encoded as a Ruby Symbol) indicating either consistency, inconsistency or errors
	def self.create_meeting(start_date, end_date, title, abstract, location, user)
		if start_date >= end_date
			return {meeting: nil, meeting_participation: nil, status: :errors}
		end

		meeting_data = insert_meeting({start_date: start_date, end_date: end_date, location: location}, user)

		####### Store the meeting and the meeting participation
		meeting = Meeting.new({start_date: start_date, end_date: end_date, title: title, location: location, abstract: abstract})
		meeting_participation = MeetingParticipation.new
		meeting_participation.meeting = meeting
		meeting_participation.is_admin = true
		meeting_participation.user = user
		meeting_participation.is_consistent = meeting_data[:is_consistent]
		meeting_participation.response_status = MeetingParticipation::Response_statuses[:accepted]

		####### If meeting participation is not consistent break out of this function
		if meeting_data[:is_consistent] == false
			sleep 5 if (ENV.fetch("RAILS_ENV") { "development" } == "test") # Fix needed to handle nested transactions
			ActiveRecord::Base.transaction do
				meeting.save
				meeting_participation.save
				meeting_data[:conflict_set].each do |id|
					# insert in conflict set
					MeetingParticipationConflict.create({meeting_participation_1_id: meeting_participation.id, meeting_participation_2_id: id})
				end
			end
			return {meeting: meeting, meeting_participation: meeting_participation, status: :inconsistent}
		end

		#######################
		# From here on we are dealing with only consistent meeting participations
		#######################

		####### Store the arriving travel
		arriving_travel, arriving_travel_steps = store_travel meeting_data[:arriving_travel]

		# Link the starting default location if needed
		arriving_travel.starting_location_dl = meeting_data[:arriving_from_dl] if meeting_data[:arriving_from_dl]

		# Update the leaving travel of the last meeting before the new one if needed
		if meeting_data[:link_before_meeting]
			meeting_data[:before_meeting].leaving_travel = arriving_travel
		end
		valid_before_meeting = (!meeting_data[:link_before_meeting] or meeting_data[:before_meeting].valid?)

		####### Store the leaving travel
		leaving_travel, leaving_travel_steps = store_travel meeting_data[:leaving_travel]

		# Link the ending default location if needed
		leaving_travel.ending_location_dl = meeting_data[:leaving_to_dl] if meeting_data[:leaving_to_dl]

		# Update the arriving travel of the first meeting after the new one if needed
		if meeting_data[:link_after_meeting]
			meeting_data[:after_meeting].arriving_travel = leaving_travel
		end
		valid_after_meeting = (!meeting_data[:link_after_meeting] or meeting_data[:after_meeting].valid?)

		meeting_participation.arriving_travel = arriving_travel
		meeting_participation.leaving_travel = leaving_travel

		####### If everything can be successfully validated, persist it on the db
		if [meeting.valid?, meeting_participation.valid?, arriving_travel.valid?, leaving_travel.valid?,
			valid_before_meeting, valid_after_meeting].all?
			ActiveRecord::Base.transaction do
				meeting.save
				meeting_participation.save
				arriving_travel.save
				arriving_travel_steps.each do |step| step.save end
				leaving_travel.save
				leaving_travel_steps.each do |step| step.save end
				if meeting_data[:link_before_meeting]
					meeting_data[:before_meeting].save
				end
				if meeting_data[:link_after_meeting]
					meeting_data[:after_meeting].save
				end
			end

			BreakHelper.update_all_breaks(arriving_travel.start_time, leaving_travel.end_time, user)

			return {meeting: meeting, meeting_participation: meeting_participation, status: :consistent}
		else
			# Print errors
			Rails.logger.debug "------------ ERRORS (MeetingHelper.create_meeting) ------------"
			Rails.logger.debug "Meeting has errors" unless meeting.valid?
			Rails.logger.debug "Meeting participation has errors" unless meeting_participation.valid?
			Rails.logger.debug "Arriving travel has errors" unless arriving_travel.valid?
			Rails.logger.debug "Leaving travel has errors" unless leaving_travel.valid?
			Rails.logger.debug "Before meeting has errors" unless valid_before_meeting
			Rails.logger.debug "After meeting has errors" unless valid_after_meeting
			Rails.logger.debug "------------ ERRORS (MeetingHelper.create_meeting) ------------"
			return {meeting: nil, meeting_participation: nil, status: :errors}
		end
	end

	# This function has to be called to create only a meeting_participation (for an already existing meeting) and store it on the db.
	# 
	# In practice, use this only for the invited users and not for the user that creates a meeting
	#
	# * meeting must be a Meeting already saved in the db
	# * user must be a User
	#
	# returns a hash containing the meeting_participation (nil in case of errors) and a status flag (encoded as a Ruby Symbol) 
	# indicating either consistency, inconsistency or errors
	def self.invite_to_meeting(meeting, user)
		meeting_data = insert_meeting({start_date: meeting.start_date, end_date: meeting.end_date, location: meeting.location}, user)

		####### Store the meeting participation
		meeting_participation = MeetingParticipation.new
		meeting_participation.meeting = meeting
		meeting_participation.is_admin = false
		meeting_participation.user = user
		meeting_participation.is_consistent = meeting_data[:is_consistent]
		meeting_participation.response_status = MeetingParticipation::Response_statuses[:pending]

		####### If meeting participation is not consistent break out of this function
		if meeting_data[:is_consistent] == false
			ActiveRecord::Base.transaction do
				meeting_participation.save
				meeting_data[:conflict_set].each do |id|
					# insert in conflict set
					MeetingParticipationConflict.create({meeting_participation_1_id: meeting_participation.id, meeting_participation_2_id: id})
				end
			end
			return {meeting_participation: meeting_participation, status: :inconsistent}
		end

		#######################
		# From here on we are dealing with only consistent meeting participations
		#######################

		####### Store the arriving travel
		arriving_travel, arriving_travel_steps = store_travel meeting_data[:arriving_travel]

		# Link the starting default location if needed
		arriving_travel.starting_location_dl = meeting_data[:arriving_from_dl] if meeting_data[:arriving_from_dl]

		# Update the leaving travel of the last meeting before the new one if needed
		if meeting_data[:link_before_meeting]
			meeting_data[:before_meeting].leaving_travel = arriving_travel
		end
		valid_before_meeting = (!meeting_data[:link_before_meeting] or meeting_data[:before_meeting].valid?)

		####### Store the leaving travel
		leaving_travel, leaving_travel_steps = store_travel meeting_data[:leaving_travel]

		# Link the ending default location if needed
		leaving_travel.ending_location_dl = meeting_data[:leaving_to_dl] if meeting_data[:leaving_to_dl]

		# Update the arriving travel of the first meeting after the new one if needed
		if meeting_data[:link_after_meeting]
			meeting_data[:after_meeting].arriving_travel = leaving_travel
		end
		valid_after_meeting = (!meeting_data[:link_after_meeting] or meeting_data[:after_meeting].valid?)

		meeting_participation.arriving_travel = arriving_travel
		meeting_participation.leaving_travel = leaving_travel

		####### If everything can be successfully validated, persist it on the db
		if [meeting_participation.valid?, arriving_travel.valid?, leaving_travel.valid?,
			valid_before_meeting, valid_after_meeting].all?
			ActiveRecord::Base.transaction do
				meeting_participation.save
				arriving_travel.save
				arriving_travel_steps.each do |step| step.save end
				leaving_travel.save
				leaving_travel_steps.each do |step| step.save end
				if meeting_data[:link_before_meeting]
					meeting_data[:before_meeting].save
				end
				if meeting_data[:link_after_meeting]
					meeting_data[:after_meeting].save
				end
			end
			return {meeting_participation: meeting_participation, status: :consistent}
		else
			# Print errors
			Rails.logger.debug "------------ ERRORS (MeetingHelper.invite_to_meeting) ------------"
			Rails.logger.debug "Meeting participation has errors" unless meeting_participation.valid?
			Rails.logger.debug "Arriving travel has errors" unless arriving_travel.valid?
			Rails.logger.debug "Leaving travel has errors" unless leaving_travel.valid?
			Rails.logger.debug "Before meeting has errors" unless valid_before_meeting
			Rails.logger.debug "After meeting has errors" unless valid_after_meeting
			Rails.logger.debug "------------ ERRORS (MeetingHelper.invite_to_meeting) ------------"
			return {meeting_participation: nil, status: :errors}
		end
	end

	# Update the schedule after accepting the invitation to a meeting
	#
	# * meeting_participations is a MeetingParticipation
	# * user is a User
	def self.accept_invitation(meeting_participation, user)
		update_schedule([meeting_participation])
	end

	# Update the schedule after declining the invitation to a meeting
	# 
	# As a result some other MeetingParticipations may become consistent
	#
	# * meeting_participation is a MeetingParticipation
	# * user is a User

Travlendar/app/views/meeting/new.html.erb
<%= render 'shared/header', selected: 'calendar' %>
<div id="content">

	<%= render 'shared/calendar_sidebar' %>
	<section class="mainContent">

		<%= render 'shared/title_back_action', title: 'Create Meeting' %>

		<div id="emailPasswordContainer">

			<%= form_with scope: :meeting, local: true do |form| %>


				<%= form.label :title, class: 'label' %>
				<%= form.text_field :title, id: 'title', type: 'text' %>
				<%= form.label :abstract, class: 'label' %>
				<%= form.text_area :abstract, id: 'abstract', type: 'text' %>
				<div class='date-time-container'>
					<div class='date-container'>
						<%= form.label :date, class: 'label' %>
						<%= form.text_field :date, id: 'date', type: 'text' %>
					</div>
					<div class='time-container'>
						<%= form.label :start_time, class: 'label' %>
						<%= form.text_field :start_time, class: 'time', id: 'start_date', type: 'text' %>
					</div>
					<div class='time-container'>
						<%= form.label :end_time, class: 'label' %>
						<%= form.text_field :end_time, class: 'time', id: 'end_date', type: 'text' %>
					</div>
				</div>

				<%= render 'shared/get_location', form: form %>
				<%= render 'shared/get_user2', form: form %>

				<div id="buttonsContainer">
					<%= form.submit 'Create Meeting', class: 'monoConfirmationButton' %>
				</div>

			<% end %>
		</div>

	</section>
</div>
<%= render 'shared/footer', selected: 'create-meeting' %>

<script type="text/javascript">

	<% if !@meeting.valid? %>
	$(window).on('load', function () {
		<% @meeting.errors.each do |error, message| %>
		displayError("<%= error.to_s %>", "<%= message %>");
		<% end %>
	})
	<% end %>
</script>


<script>
	$(function () {
		$('#start_date').timepicker({'step': 5});

		$('#start_date').on('changeTime', function () {
			var start_time_value = $('#start_date').val();
			$('#end_date').timepicker({
				'step': 5,
				'minTime': start_time_value,
				'maxTime': '11.55pm',
				'showDuration': true
			});
		});
		$('#end_date').timepicker({
			'step': 5,
			'minTime': '00.00am',
			'maxTime': '11.55pm',
			'showDuration': true,
			'timeFormat': 'H:i'
		});
	});

	$(function () {
		$("#date").datepicker({
			dateFormat: "yy/mm/dd"
		});
	});

</script>

<%= render 'shared/timepicker'  %>

Travlendar/app/views/meeting/participants_page.html.erb
<%= render 'shared/header' %>
<div id="content">
	<script type="text/javascript"></script>
	<%= render 'shared/calendar_sidebar' %>
	<section class="mainContent">
		<%= render 'shared/title_back_action', title: 'Participant List', path: @meeting %>

		<% write_something = false %>
		<% if @meeting.get_participants(1).count > 1 #1 becouse I'm in the participants    %>
			<% write_something = true %>
			<h2>
				ACCEPTED
			</h2>
			<div>
				<% @meeting.get_participants(1).each do |meeting_participant| %>
					<% unless meeting_participant.user.id == @user.id %>
						<div class="colored-container light-blue-container participant-container">
							<%= meeting_participant.get_name_surname %>
							(<%= meeting_participant.user.nickname %>)
							<%= link_to user_path(id: meeting_participant.user.id) do %>
								<div id="onlyadmin" class='right-buttons colored-container light-grey-container'>
									View Profile
								</div>
							<% end %>
							<%= link_to remove_from_meeting_path(meeting_id: @meeting.id, user_id: meeting_participant.user.id) do %>
								<div class='right-buttons colored-container light-grey-container only-admin'>
									Remove
								</div>
							<% end %>
							<% unless meeting_participant.is_admin %>
								<%= link_to nominate_admin_path(meeting_id: @meeting.id, user_id: meeting_participant.user.id) do %>
									<div class='right-buttons colored-container light-grey-container only-admin'>
										Nominate
									</div>
								<% end %>
							<% end %>

						</div>
					<% end %>
				<% end %>
			</div>
		<% end %>
		<% if @meeting.get_participants(0).count > 0 %>
			<% write_something = true %>
			<h2>
				PENDING
			</h2>
			<div>
				<% @meeting.get_participants(0).each do |meeting_participant| %>
					<div class="colored-container light-blue-container participant-container">
						<%= meeting_participant.get_name_surname %>
						(<%= meeting_participant.user.nickname %>)
						<%= link_to user_path(id: meeting_participant.user.id) do %>
							<div id="onlyadmin" class='right-buttons colored-container light-grey-container'>
								View Profile
							</div>
						<% end %>
					</div>
				<% end %>
			</div>
		<% end %>
		<% if @meeting.get_participants(2).count > 0 %>
			<% write_something = true %>
			<h2>
				DECLINED
			</h2>
			<div>
				<% @meeting.get_participants(2).each do |meeting_participant| %>
					<div class="colored-container light-blue-container participant-container">
						<%= meeting_participant.get_name_surname %>
						(<%= meeting_participant.user.nickname %>)
						<%= link_to user_path(id: meeting_participant.user.id) do %>
							<div id="onlyadmin" class='right-buttons colored-container light-grey-container'>
								View Profile
							</div>
						<% end %>
					</div>
				<% end %>
			</div>
		<% end %>
		<% unless write_something %>
			<h2>
				You are the only participant; this is an instant meeting!
			</h2>
		<% end %>
	</section>
</div>
<%= render 'shared/footer' %>

<script type="text/javascript">
	<% unless  @meeting.get_meeting_participaton(@user).is_admin %>
		$('.only-admin').hide();
	<% end %>
</script>

Travlendar/app/views/meeting/show.html.erb
<%= render 'shared/header', selected: 'calendar' %>
<div id="content">
	<%= render 'shared/calendar_sidebar' %>
	<section class="mainContent">
		<%= render 'shared/title_back_action', title: @meeting.title, path: @back_path %>
		<% unless @meeting.abstract.blank? %>
			<div class="abstract-container">
				<h3>
					<%= @meeting.abstract %>
				</h3>
			</div>
		<% end %>
		<div class="date-time-block-container">
			<div class="colored-container light-blue-container date-time-block">
				<%= @meeting.start_date.strftime("%m/%d/%Y") %>
			</div>
			<div class="colored-container light-blue-container date-time-block">
				<%= @meeting.start_date.strftime("%I:%M%p") + " - " + @meeting.end_date.strftime("%I:%M%p") %>
			</div>
		</div>

		<!--
		<div id="location" class="location-block-container" onclick="goToLocation(<%= @meeting.location.latitude %>,<%= @meeting.location.longitude %>)">
			<%= image_tag("meeting_page/location_icon.png", id: "location_icon", class: "location-block") %>
			<div class="location-description-block">
				<%= @meeting.location.description %>
			</div>
		</div>
		-->

		<div id="map-container">
			<%= render 'shared/google_map', latitude: @meeting.location.latitude, longitude: @meeting.location.longitude, name: @meeting.title %>
		</div>

		<div class="date-time-block-container">
			<ul class="colored-container light-grey-container date-time-block">
				<%= link_to('View Participants', participants_page_path(@meeting), id: @profile) %>
			</ul>
		</div>

		<div class="response-block-container only-pending">
			<%= link_to "ACCEPT", accept_meeting_path(meeting_id: @meeting.id, user_id: @user.id), class: "single-response-button light-grey-container colored-container" %>
			<%= link_to "DECLINE", decline_meeting_path(meeting_id: @meeting.id, user_id: @user.id), class: "single-response-button light-grey-container colored-container" %>
			<div class="single-response-button light-grey-container colored-container"> RESCHEDULE</div>
		</div>
	</section>
</div>
<%= render 'shared/footer' %>



<script type="text/javascript">
	<% unless  @meeting.get_meeting_participaton(@user).response_status == 0 %>
	$('.only-pending').hide();
	<% end %>
</script>