Travlendar/config/routes.rb
Rails.application.routes.draw do

	resources :user
	resources :meeting
	resources :notification, only: [:index]
	resources :default_location


	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get '/' => 'homepage#index', as: 'homepage'
	post '/' => 'homepage#post_index', as: 'root_post'
	post '/user/new', to: 'user#create'
	delete '/logout', to: 'homepage#destroy'

	# User
	get 'user/new'
	post 'user/:id/edit', to: 'user#post_edit'
	get 'user/search/:id' => 'user#search', as: 'search_user'
	get 'user/search_contacts/:id' => 'user#search_contacts', as: 'search_user_contact'
	get 'user/contacts/:id' => 'user#contacts', as: 'contacts_page'
	get 'user/remove_from_contacts/:user_id/:to_delete_id' => 'user#delete_contact', as: 'delete_contact'
	get 'user/add_to_contacts/:user_id/:to_add_id' => 'user#add_contact', as: 'add_contact'
	get 'user/:id/settings' => 'user#settings', as: 'settings_page'
	patch 'user/:id/settings/change_preference_list' => 'user#change_preference_list', as: 'change_preference_list'
	get 'user/:id/add_constraint' => 'user#add_constraint', as: 'add_constraint'
	post 'user/:id/add_constraint', to: 'user#create_constraint'
	get 'user/delete_constraint/:user_id/:constraint_id' => 'user#delate_constraint', as: 'delete_constraint'
	get 'user/delete_email/:user_id/:email_id' => 'user#delete_email', as: 'delete_email'
	get 'user/delete_social/:user_id/:social_user_id' => 'user#delete_social', as: 'delete_social'

	# Meeting
	get 'meeting/:id/participants_page' => 'meeting#participants_page', as: 'participants_page'
	get 'meeting/remove_participant/:meeting_id/:user_id' => 'meeting#remove_from_meeting', as: 'remove_from_meeting'
	get 'meeting/nominate_admin/:meeting_id/:user_id' => 'meeting#nominate_admin', as: 'nominate_admin'
	post '/meeting/new', to: 'meeting#create'
	get 'meeting/accept_participation/:meeting_id/:user_id' => 'meeting#accept', as: 'accept_meeting'
	get 'meeting/decline_participation/:meeting_id/:user_id' => 'meeting#decline', as: 'decline_meeting'

	# Calendar Page
	get 'calendar/day/:year/:month/:day' => 'calendar#show_day', constraints: {year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/}, as: 'calendar_day', defaults: {year: DateTime.now.year, month: DateTime.now.month, day: DateTime.now.day}
	get 'calendar/week/:year/:week' => 'calendar#show_week', constraints: {year: /\d{4}/, week: /\d{1,2}/}, as: 'calendar_week'
	get 'calendar/month/:year/:month' => 'calendar#show_month', constraints: {year: /\d{4}/, month: /\d{1,2}/}, as: 'calendar_month'

	# Travel
	get 'travel/:id' => 'travel#show', as: 'show_travel'

	# Notification
	get 'notification/resolve_warning/:meeting_participation_id' => 'notification#resolve_warning', as: 'resolve_warning'

	# Default Location
	post 'default_location/new', to: 'default_location#create'
	get 'default_location/delete_dl/:default_location_id/:user_id' => 'default_location#delete', as: 'delete_default_location'
	get 'default_location/first_def_location/:user_id' => 'default_location#first_def_location', as: 'create_first_def_location'
	post 'default_location/first_def_location/:user_id', to: 'default_location#first_creation'

	# Break
	get 'break/:id/add_break' => 'break#add_break', as: 'add_break'
	post 'break/:id/add_break', to: 'break#create_break'
	get 'user/delete_break/:user_id/:break_id' => 'break#delete_break', as: 'delete_break'
end

Travlendar/app/views/shared/_calendar_sidebar.html.erb
<% if params[:year].nil? %>
	<% year = DateTime.now.year %>
<% else %>
	<% year = params[:year] %>
<% end %>

<section class="sidebar">
	<% for month in 1..12 %>
		<%= render 'shared/month_calendar', year: year.to_i, month: month %>
	<% end %>
</section>

Travlendar/app/views/shared/_get_location.html.erb
<%= form.label :location, class: 'label' %>
<%= form.text_field :location, type: 'hidden', value: @location, id: "location-hidden" %>

<script>

	// This example displays an address form, using the autocomplete feature
	// of the Google Places API to help users fill in the information.

	// This example requires the Places library. Include the libraries=places
	// parameter when you first load the API. For example:
	// <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

	var placeSearch, autocomplete;

	function initAutocomplete() {
		// Create the autocomplete object, restricting the search to geographical
		// location types.
		autocomplete = new google.maps.places.Autocomplete(
			/** @type {!HTMLInputElement} */(document.getElementById('location')),
			{types: ['geocode']});

		// When the user selects an address from the dropdown, populate the address
		// fields in the form.
		autocomplete.addListener('place_changed', fillInAddress);
	}

	function fillInAddress() {
		// Get the place details from the autocomplete object.
		var place = autocomplete.getPlace();
		var lat = place.geometry.location.lat();
		var lng = place.geometry.location.lng();
		var name = place.name;

		$('#location-hidden').val(lat + "," + lng + "," + name);

	}

	// Bias the autocomplete object to the user's geographical location,
	// as supplied by the browser's 'navigator.geolocation' object.
	function geolocate() {
		if (navigator.geolocation) {
			navigator.geolocation.getCurrentPosition(function (position) {
				var geolocation = {
					lat: position.coords.latitude,
					lng: position.coords.longitude
				};
				var circle = new google.maps.Circle({
					center: geolocation,
					radius: position.coords.accuracy
				});
				autocomplete.setBounds(circle.getBounds());
			});
		}
	}

</script>

<div id="locationField">
	<input id="location" placeholder="Enter your address"
				 onFocus="geolocate()" type="text">
</div>

<!-- Replace the value of the key parameter with your own API key. -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA3MT_tKqlAWC3GjlcVLuWqK7CDWLio7tE&libraries=places&callback=initAutocomplete"
				async defer></script>

Travlendar/app/views/shared/_get_user.html.erb
<%= form.label :participants, class: 'label' %>
<%= form.text_field :participants, type: 'hidden', value: @user_selected, id: "users-hidden"%>

<%
	user_names = []
	@users.each do |u|
		user_names.push(u.name + " " + u.surname + " (" + u.nickname + ")")
	end
%>
<div id="invited_user_content">
</div>
<%= content_tag :div, id: "temp_information", data: {user: user_names} do %>
	<input type="text" id="search", placeholder="Write user name or nickname">
<% end %>

<script>
	$(function () {
		var users = $('#temp_information').data('user')
		$("#search").autocomplete({
			source: users,
			select: function (event, ui) {
				var content = $('#users-hidden').val()
				content = content + ',' + (ui.item.value)
				$('#users-hidden').val(content);

				var $label = $("<label class='colored-container light-blue-container participants-list'>").text(ui.item.value);
				$('#invited_user_content').append($label);
			}
		});
	});

</script>

Travlendar/app/views/shared/_google_map.html.erb
<div id="map"></div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpdtTuFPC3MwAUIakfyrP_Bmw0Itb2lS4&callback=initMap"
				async defer></script>

<script type="text/javascript">
	var map;
	var name = "<%= name %>";
  	var latitude = <%= latitude %>;
  	var longitude = <%= longitude %>;
	function initMap() {
		map = new google.maps.Map(document.getElementById('map'), {
			center: {lat: latitude, lng: longitude},
			zoom: 15
		});

	  var marker = new google.maps.Marker({
		  position: {lat: latitude, lng: longitude},
		  map: map,
		  title: name
	  });
	}
</script>

<style type="text/css">
	/* Always set the map height explicitly to define the size of the div
 * element that contains the map. */

	#map{
		height: 100%;
	}

</style>

Travlendar/app/views/shared/_header.html.erb
<% unless defined? selected %>
	<% selected = nil %>
<% end %>

<header>
	<%= link_to calendar_day_path, id: "logo-a" do %>
		<div id="logo">
			Travlendar+
		</div>
	<% end %>

	<div id="headerLinks">
		<a href="<%= user_path id: current_user.id %>" title="Profile" class="<%= if selected == 'profile' then 'selected' end %>">Profile</a><!---
		--><a href="<%= calendar_day_path %>" title="Calendar" class="<%= if selected == 'calendar' then 'selected' end %>">Calendar</a><!---
		--><a href="<%= settings_page_path id: current_user.id %>" title="Settings" class="<%= if selected == 'settings' then 'selected' end %>">Settings</a><!---
		--><a href="<%= notification_index_path %>" title="Notifications" class="<%= if selected == 'notifications' then 'selected' end %>">
			<div>Notifications</div>
			<div id="notifications-amount">
				<%= current_user.meeting_participations.where(response_status:
							 MeetingParticipation::Response_statuses[:pending]).count +
				   current_user.meeting_participations.where(is_consistent: false,
				   			response_status: MeetingParticipation::Response_statuses[:accepted]).count +
				   current_user.computed_breaks.where(is_doable: false).count %>
			</div>
		</a>
	</div>
</header>

Travlendar/app/views/shared/_location_with_map.html.erb
<p><%= form.label :location, class: 'label' %></p>
<%= form.text_field :location, type: 'hidden', value: @location, id: "location-hidden" %>

<div class="pac-card" id="pac-card">
	<div>
	</div>
	<div id="pac-container">
		<input id="pac-input" type="text"
					 placeholder="Enter a location">
	</div>
</div>
<div id="map"></div>
<div id="infowindow-content">
	<img src="" width="16" height="16" id="place-icon">
	<span id="place-name" class="title"></span><br>
	<span id="place-address"></span>
</div>


<style>
	/* Always set the map height explicitly to define the size of the div
	 * element that contains the map. */
	#map {
		height: 100%;
	}

	/* Optional: Makes the sample page fill the window. */
	html, body {
		height: 100%;
		margin: 0;
		padding: 0;
	}

	#description {
		font-family: Roboto;
		font-size: 15px;
		font-weight: 300;
	}

	#infowindow-content .title {
		font-weight: bold;
	}

	#infowindow-content {
		display: none;
	}

	#map #infowindow-content {
		display: inline;
	}

	.pac-card {
		margin: 10px 10px 0 0;
		border-radius: 2px 0 0 2px;
		box-sizing: border-box;
		-moz-box-sizing: border-box;
		outline: none;
		box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
		background-color: #fff;
		font-family: Roboto;
	}

	#pac-container {
		padding-bottom: 12px;
		margin-right: 12px;
	}

	.pac-controls {
		display: inline-block;
		padding: 5px 11px;
	}

	.pac-controls label {
		font-family: Roboto;
		font-size: 13px;
		font-weight: 300;
	}

	#pac-input {
		background-color: #fff;
		font-family: Roboto;
		font-size: 15px;
		font-weight: 300;
		margin-left: 12px;
		padding: 0 11px 0 13px;
		text-overflow: ellipsis;
		width: 400px;
	}

	#pac-input:focus {
		border-color: #4d90fe;
	}

	#title {
		color: #fff;
		background-color: #4d90fe;
		font-size: 25px;
		font-weight: 500;
		padding: 6px 12px;
	}
</style>

<script>
	// This example requires the Places library. Include the libraries=places
	// parameter when you first load the API. For example:
	// <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

	function initMap() {
		var map = new google.maps.Map(document.getElementById('map'), {
			center: {lat: -33.8688, lng: 151.2195},
			zoom: 13
		});
		var card = document.getElementById('pac-card');
		var input = document.getElementById('pac-input');
		var types = document.getElementById('type-selector');
		var strictBounds = document.getElementById('strict-bounds-selector');

		map.controls[google.maps.ControlPosition.TOP_RIGHT].push(card);

		var autocomplete = new google.maps.places.Autocomplete(input);

		// Bind the map's bounds (viewport) property to the autocomplete object,
		// so that the autocomplete requests use the current map bounds for the
		// bounds option in the request.
		autocomplete.bindTo('bounds', map);

		var infowindow = new google.maps.InfoWindow();
		var infowindowContent = document.getElementById('infowindow-content');
		infowindow.setContent(infowindowContent);
		var marker = new google.maps.Marker({
			map: map,
			anchorPoint: new google.maps.Point(0, -29)
		});

		autocomplete.addListener('place_changed', function () {
			infowindow.close();
			marker.setVisible(false);
			var place = autocomplete.getPlace();
			if (!place.geometry) {
				// User entered the name of a Place that was not suggested and
				// pressed the Enter key, or the Place Details request failed.
				window.alert("No details available for input: '" + place.name + "'");
				return;
			}

			// put the selected value in the hidden input
			var lat = place.geometry.location.lat();
			var lng = place.geometry.location.lng();
			var name = place.name;

			$('#location-hidden').val(lat + "," + lng + "," + name);


			// If the place has a geometry, then present it on a map.
			if (place.geometry.viewport) {
				map.fitBounds(place.geometry.viewport);
			} else {
				map.setCenter(place.geometry.location);
				map.setZoom(17);  // Why 17? Because it looks good.
			}
			marker.setPosition(place.geometry.location);
			marker.setVisible(true);

			var address = '';
			if (place.address_components) {
				address = [
					(place.address_components[0] && place.address_components[0].short_name || ''),
					(place.address_components[1] && place.address_components[1].short_name || ''),
					(place.address_components[2] && place.address_components[2].short_name || '')
				].join(' ');
			}

			infowindowContent.children['place-icon'].src = place.icon;
			infowindowContent.children['place-name'].textContent = place.name;
			infowindowContent.children['place-address'].textContent = address;
			infowindow.open(map, marker);
		});


	}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA3MT_tKqlAWC3GjlcVLuWqK7CDWLio7tE&libraries=places&callback=initMap"
				async defer></script>

Travlendar/app/views/shared/_menu_three_lines.html.erb
<div class="menu-three-lines" style="height: fit-content; width: 15px;">
	<div style="width: 100%; margin-bottom: 2px; height: 3px; background-color: black;"></div>
	<div style="width: 100%; margin-bottom: 2px; height: 3px; background-color: black;"></div>
	<div style="width: 100%; height: 3px; background-color: black;"></div>
</div>

Travlendar/app/views/shared/_month_calendar.html.erb
<%
	first_of_month = DateTime.new(year, month)
	last_of_month = first_of_month + 1.months - 1.days
	from_date = first_of_month - (first_of_month.wday - 1).days
	end_date = last_of_month + ((7 - last_of_month.wday) % 7).days
%>

<div class="calendar-month">
	<table>
		<tr class="month">
			<th colspan="7">
				<a href="<%= calendar_month_path year, month %>"><%= first_of_month.strftime "%B %Y" %></a>
			</th>
		</tr>
		<tr>
			<th>Mon</th>
			<th>Tue</th>
			<th>Wed</th>
			<th>Thu</th>
			<th>Fri</th>
			<th>Sat</th>
			<th>Sun</th>
		</tr>
		<tr>
			<% first = true %>
			<% for date in from_date..end_date %>
				<% if date.wday == 1 and !first %>
					<td>
						<a href="<%= calendar_week_path date.year, (date - 4.days).cweek %>">
							<%= image_tag "week_icon.svg", class: 'week-icon' %>
						</a>
					</td>
					</tr>
					<tr>
				<% end %>
				<% first = false %>
				<% if date.month == month %>
					<td>
						<a href="<%= calendar_day_path date.year, date.month, date.day %>"><%= date.strftime "%d" %></a>
					</td>
				<% else %>
					<td></td>
				<% end %>
			<% end %>
			<td>
				<a href="<%= calendar_week_path year, last_of_month.cweek %>">
					<%= image_tag "week_icon.svg", class: 'week-icon' %>
				</a>
			</td>
			</tr>
			</table>
</div>

Travlendar/app/views/shared/_new_constraint.html.erb
<%= form_with scope: :constraint, local: true do |form| %>


	<%= form.label :travel_mean, class: 'label' %>
	<%= form.text_field :travel_mean, id: 'travel-mean', type: 'text' %>

	<div id="buttonsContainer">
		<%= form.submit 'Create Constraint', class: 'monoConfirmationButton' %>
	</div>
<% end %>

Travlendar/app/views/shared/_new_default_location.html.erb
<div id="emailPasswordContainer">

	<%= form_with scope: :default_location, local: true do |form| %>


		<%= form.label :name, class: 'label' %>
		<%= form.text_field :name, id: 'name', type: 'text' %>
		<div class='date-time-container'>
			<div class='date-container'>
				<%= form.label :day_of_the_week, class: 'label', value: 'Day Of The Week' %>
				<%= form.text_field :day_of_the_week, id: 'day_of_the_week', type: 'text', onfocus: "javascript:$(this).autocomplete('search','');" %>
			</div>
			<div class='time-container'>
				<%= form.label :starting_hour, class: 'label' %>
				<%= form.text_field :starting_hour, class: 'time', id: 'starting_hour', type: 'text' %>
			</div>

		</div>

		<div id="full-map-container">
			<%= render 'shared/location_with_map', form: form %>
		</div>

		<div id="emailPasswordContainer" style="margin-top: 33px;">
			<div class="radio-button-container">
				<label for="daily">Daily</label>
				<%= radio_button("repetition", "day_of_the_week", "daily", options = {id: 'daily'}) %>
				<label for="weekly">Weekly</label>
				<%= radio_button("repetition", "day_of_the_week", "weekly", options = {checked: true, id: 'weekly'}) %>
			</div>
			<div id="buttonsContainer">
				<%= form.submit 'Create Default Location', class: 'monoConfirmationButton' %>
			</div>

	<% end %>
	</div>

	<script>
	  $(function () {
		  $('#starting_hour').timepicker({'step': 5});
	  });


	  $(function () {
		  var users = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
		  $("#day_of_the_week").autocomplete({
			  source: users,
			  minLength: 0
		  });
	  });

	</script>


	<script type="text/javascript">

	  <% if !@default_location.valid? %>
	  $(window).on('load', function () {
		  <% @default_location.errors.each do |error, message| %>
		  displayError("<%= error.to_s %>", "<%= message %>");
		  <% end %>
	  })
	  <% end %>
	</script>

<%= render 'shared/timepicker' %>

Travlendar/app/views/shared/_preference_list.html.erb
<%= form.text_field :preference_list, type: 'hidden', value: @user.preference_list, id: "pref-list-hidden" %>

<div id='preference_list'>
	<ul id="prefList_active" class="connectedSortable ui-sortable preference-list-ul">
		<li class="ui-state-default ui-sortable-handle preference-list-li" value=0>Walking <%= render 'shared/menu_three_lines' %></li>
		<li class="ui-state-default ui-sortable-handle preference-list-li" value=1>Driving <%= render 'shared/menu_three_lines' %></li>
		<li class="ui-state-default ui-sortable-handle preference-list-li" value=2>Public Transportation <%= render 'shared/menu_three_lines' %></li>
		<li class="ui-state-default ui-sortable-handle preference-list-li" value=3>Biking <%= render 'shared/menu_three_lines' %></li>
	</ul>

	<ul id="prefList_inactive" class="connectedSortable ui-sortable preference-list-ul">
	</ul>
</div>

<script type="text/javascript">
	$(function () {
		$("#prefList_active, #prefList_inactive").sortable({
			connectWith: ".connectedSortable",
			update: function (event, ui) {
				$('#pref-list-hidden').val(getPreferenceList())
			},
			disabled: false
		}).disableSelection();

		var preference_list = <%= @user.preference_list.chars.map {|c| c.to_i} %>;

		if (preference_list != [0, 1, 2, 3]) {
			preference_list.forEach(function (el, index) {
				var element = $('.preference-list-li[value=' + el + ']');
				$('#prefList_active').append(element)
			});
			for (var i = 0; i < 4; i++) {
				if (preference_list.indexOf(i) < 0) {
					var element = $('.preference-list-li[value=' + i + ']');
					$('#prefList_inactive').append(element)
				}
			}
		}
	});

	function getPreferenceList() {
		var prefList = '';
		$('#prefList_active .preference-list-li').each(function (index, el) {
			prefList += el.value
		});
		return prefList
	}
</script>

<style>
	.preference-list-ul {
		background-color: #9BC8DA;
		list-style-type: none;
		padding: 5px;
		border-radius: 10px;
		box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
		min-height: 30px;
		text-align: left;
	}

	.preference-list-li {
		background-color: #B2B2B2;
		padding: 5px;
		border: none;
		margin: 5px;
		box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
		height: 15px;
		line-height: 15px;
		color: black;
		border-radius: 4px;
		cursor: pointer;
	}

	.menu-three-lines {
		float: right;
	}

	#preference_list.error .preference-list-ul {
		border: 1px solid red;
	}
</style>

Travlendar/app/views/shared/_sidebar.html.erb
    <section class="sidebar">
      <!-- This adds a sidebar with 1 searchbox,2 menusets, each with 4 links -->



      <p><%= @user.nickname %></p>
		<input type="text"  id="search" value="search">
      <div id="menubar">
        <nav class="menu">
          <h2><!-- Title for menuset 1 -->MENU ITEM 1 </h2>
          <hr>
          <ul>
            <!-- List of links under menuset 1 -->
            <li><a href="#" title="Link">Link 1</a></li>
            <li><a href="#" title="Link">Link 2</a></li>
            <li><a href="#" title="Link">Link 3</a></li>
            <li class="notimp"><!-- notimp class is applied to remove this link from the tablet and phone views --><a href="#"  title="Link">Link 4</a></li>
          </ul>
        </nav>
        <nav class="menu">
          <h2>MENU ITEM 2 </h2>
          <!-- Title for menuset 2 -->
          <hr>
          <ul>
            <!--List of links under menuset 2 -->
            <li><a href="#" title="Link">Link 1</a></li>
            <li><a href="#" title="Link">Link 2</a></li>
            <li><a href="#" title="Link">Link 3</a></li>
            <li class="notimp"><!-- notimp class is applied to remove this link from the tablet and phone views --><a href="#" title="Link">Link 4</a></li>
          </ul>
        </nav>
      </div>
    </section>

Travlendar/app/views/shared/_title_back_action.html.erb
<div class=" title-go-back-block">
	<div class="go-back">
		<% if defined? path %>
			<%= link_to image_tag('go_back_icon.svg', id: 'go-back-image'), path %>
		<% end %>
	</div>
	<div class="title-block title">
			<%= title %>
	</div>
	<div class="go-back"></div>
</div>

<style>
	.title {
		font-size: 40px;
		color: #575756;
		font-style: oblique;
		padding-top: 2.5%;
		padding-bottom: 3%;
	}

	.go-back{
		width: 15%;
		display: inline-block;
		padding-top: 3%;
		padding-bottom: 3%;
		display: flex; /* add */
		float: left;
		justify-content: center; /* add to align horizontal */
		align-items: center; /* add to align vertical */

	}

	.go-back a{
		height: max-content;
		text-align: center;
	}

	#go-back-image{
		width: 33px;
		top: 0;
		bottom: 0;
		left: 0;
		right: 0;
		margin: auto;
		float: left;
	}

	.title-block{
		width: 70%;
		display: inline-block;
	}

	.title-go-back-block{
		width: 100%;
		height: 97px;
		display: inline-flex;
		margin-bottom: 2%;
		margin-top: 2%;
	}


</style>