Travlendar/config/routes.rb
Rails.application.routes.draw do

	resources :user
	resources :meeting
	resources :notification, only: [:index]
	resources :default_location


	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get '/' => 'homepage#index', as: 'homepage'
	post '/' => 'homepage#post_index', as: 'root_post'
	post '/user/new', to: 'user#create'
	delete '/logout', to: 'homepage#destroy'

	# User
	get 'user/new'
	post 'user/:id/edit', to: 'user#post_edit'
	get 'user/search/:id' => 'user#search', as: 'search_user'
	get 'user/search_contacts/:id' => 'user#search_contacts', as: 'search_user_contact'
	get 'user/contacts/:id' => 'user#contacts', as: 'contacts_page'
	get 'user/remove_from_contacts/:user_id/:to_delete_id' => 'user#delete_contact', as: 'delete_contact'
	get 'user/add_to_contacts/:user_id/:to_add_id' => 'user#add_contact', as: 'add_contact'
	get 'user/:id/settings' => 'user#settings', as: 'settings_page'
	patch 'user/:id/settings/change_preference_list' => 'user#change_preference_list', as: 'change_preference_list'
	get 'user/:id/add_constraint' => 'user#add_constraint', as: 'add_constraint'
	post 'user/:id/add_constraint', to: 'user#create_constraint'
	get 'user/delete_constraint/:user_id/:constraint_id' => 'user#delate_constraint', as: 'delete_constraint'
	get 'user/delete_email/:user_id/:email_id' => 'user#delete_email', as: 'delete_email'
	get 'user/delete_social/:user_id/:social_user_id' => 'user#delete_social', as: 'delete_social'

	# Meeting
	get 'meeting/:id/participants_page' => 'meeting#participants_page', as: 'participants_page'
	get 'meeting/remove_participant/:meeting_id/:user_id' => 'meeting#remove_from_meeting', as: 'remove_from_meeting'
	get 'meeting/nominate_admin/:meeting_id/:user_id' => 'meeting#nominate_admin', as: 'nominate_admin'
	post '/meeting/new', to: 'meeting#create'
	get 'meeting/accept_participation/:meeting_id/:user_id' => 'meeting#accept', as: 'accept_meeting'
	get 'meeting/decline_participation/:meeting_id/:user_id' => 'meeting#decline', as: 'decline_meeting'

	# Calendar Page
	get 'calendar/day/:year/:month/:day' => 'calendar#show_day', constraints: {year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/}, as: 'calendar_day', defaults: {year: DateTime.now.year, month: DateTime.now.month, day: DateTime.now.day}
	get 'calendar/week/:year/:week' => 'calendar#show_week', constraints: {year: /\d{4}/, week: /\d{1,2}/}, as: 'calendar_week'
	get 'calendar/month/:year/:month' => 'calendar#show_month', constraints: {year: /\d{4}/, month: /\d{1,2}/}, as: 'calendar_month'

	# Travel
	get 'travel/:id' => 'travel#show', as: 'show_travel'

	# Notification
	get 'notification/resolve_warning/:meeting_participation_id' => 'notification#resolve_warning', as: 'resolve_warning'

	# Default Location
	post 'default_location/new', to: 'default_location#create'
	get 'default_location/delete_dl/:default_location_id/:user_id' => 'default_location#delete', as: 'delete_default_location'
	get 'default_location/first_def_location/:user_id' => 'default_location#first_def_location', as: 'create_first_def_location'
	post 'default_location/first_def_location/:user_id', to: 'default_location#first_creation'

	# Break
	get 'break/:id/add_break' => 'break#add_break', as: 'add_break'
	post 'break/:id/add_break', to: 'break#create_break'
	get 'user/delete_break/:user_id/:break_id' => 'break#delete_break', as: 'delete_break'
end

Travlendar/app/controllers/notification_controller.rb
# This class manages everything related with the notifications (warnings, invitations, undoable breaks, resolve warning)
class NotificationController < ApplicationController

	# This method supports the notification page
	def index
		@user = current_user
		@pending_meetings = get_invitation(@user)
		@warning_meeting = get_inconsistent_meetings(@user)
		@undoable_breaks = get_undoable_breaks(@user)
	end

	# This method supports the resolve warning page where a user can accept/decline meetings
	def resolve_warning
		check_if_mine(params[:meeting_participation_id])
		mp = MeetingParticipation.find(params[:meeting_participation_id])
		single_group = [mp]
		single_group = fill_inconsistency(mp, single_group)
		@meeting_participations = single_group
		@user = current_user
	end

	private

	# This method is used to retrieve all the undoable breaks
	def get_undoable_breaks(user)
		breaks = user.breaks
		undoables = ComputedBreak.where(break_id: breaks.ids, is_doable: false)

		breaks_day = []
		current_day = nil
		if undoables.count > 0
			undoables.each do |ub|
				if current_day.nil? || (ub.start_time_slot.midnight != current_day)
					# Change the current day
					current_day = ub.start_time_slot.midnight
					breaks_day.push current_day
				end
				breaks_day.push ub
			end
		end
		return breaks_day
	end

	# This method is used to retrieve all the invitations of a user
	def get_invitation(user)
		schedule = []

		meeting_participations = user.meeting_participations.joins(:meeting)
																 .where(response_status: MeetingParticipation::Response_statuses[:pending])
																 .order('meetings.start_date')
		current_day = nil

		meeting_participations.each do |mp|
			if current_day.nil? || (mp.meeting.start_date.midnight != current_day)
				# Change the current day
				current_day = mp.meeting.start_date.midnight
				schedule.push current_day
			end
			schedule.push mp.meeting # maybe push also response status??
		end
		schedule
	end

	# This method is used to retrieve all the inconsistent meetings of a user
	def get_inconsistent_meetings(user)
		list_of_all_inconsistencies = []

		inconsistent_mp = user.meeting_participations.joins(:meeting)
													.where(is_consistent: false)
													.where.not(response_status: MeetingParticipation::Response_statuses[:declined])
													.order('meetings.start_date')

		current_day = nil
		inconsistent_mp.each do |mp|

			already_present = false
			list_of_all_inconsistencies.each do |single_group|

				begin
					if single_group.include? mp
						already_present = true
						break
					end
				rescue NoMethodError
					next
				end
			end
			if already_present
				next
			end

			if current_day.nil? || (mp.meeting.start_date.midnight != current_day)
				# Change the current day
				current_day = mp.meeting.start_date.midnight
				list_of_all_inconsistencies.push current_day
			end
			single_group = [mp]
			single_group = fill_inconsistency(mp, single_group)
			list_of_all_inconsistencies.push single_group
		end
		return list_of_all_inconsistencies
	end

	# This is a support recursive method to retrieve all the inconsistent meeting linked with mp
	def fill_inconsistency(mp, single_group)
		inconsistent_to_mp = mp.conflicting_meeting_participations

		inconsistent_to_mp.each do |mp_inc|
			unless single_group.include? mp_inc
				single_group.push mp_inc
				single_group = fill_inconsistency(mp_inc, single_group)
			end
		end
		return single_group
	end

	# This method checks if the meeting participation is mine
	def check_if_mine(meeting_participation_id)
		unless current_user.meeting_participations.where(id: meeting_participation_id).count > 0
			raise ActionController::RoutingError, 'Not Found'
		end
	end
end

Travlendar/app/views/notification/index.html.erb
<%= render 'shared/header', selected: 'notifications' %>
<div id="content">
	<script type="text/javascript"></script>
	<%= render 'shared/calendar_sidebar' %>
	<section class="mainContent">

		<%= render 'shared/title_back_action', title: 'Notifications Page' %>

		<% first = true %>
		<h2>
			WARNINGS
		</h2>
		<% @warning_meeting.each do |warning_mps| %>
			<% if warning_mps.is_a? Array %>

				<div class="warning-container colored-container light-grey-container" id=<%= warning_mps[0].id %>>
					<% warning_mps.each do |single_warning_mp| %>
						<% meeting = single_warning_mp.meeting %>
						<div class="single-warning meeting rounded-box">
							<div class="meeting-date">
								<%= meeting.start_date.strftime "%I:%M %p" %>
								-
								<%= meeting.end_date.strftime "%I:%M %p" %></div>
							<div class="meeting-title"><%= meeting.title %></div>
							<div class="meeting-location"><%= meeting.location.description %></div>
						</div>
					<% end %>
				</div>

			<% else %>
				<% if first %>
					<% first = false %>
				<% else %>
					</div>
				<% end %>
				<% item = warning_mps %>
				<div class="date-separator rounded-box" id="<%= item.strftime '%Y%m%d' %>-w-separator" onclick="toggle('<%= item.strftime "%Y%m%d" %>-w')">
					<div><%= item.strftime "%a %d %b %Y" %></div>
				</div>
				<div id="<%= item.strftime '%Y%m%d' %>-w-accordion" class="date-accordion">
					<script type="text/javascript">
			  $(window).on('load', function () {
				  setMaxHeight("<%= item.strftime '%Y%m%d' %>-w")
			  })
					</script>
			<% end %>
		<% end %>
		</div>
		<% if @pending_meetings.count > 0 %>

			<% first = true %>

			<h2>
				INVITATIONS PENDING
			</h2>
			<div>
				<% @pending_meetings.each do |item| %>
					<% if item.is_a? Meeting %>
						<% meeting = item %>
						<div class="meeting-invitation">
							<div class="meeting rounded-box">
								<div class="meeting-date"><%= meeting.start_date.strftime "%I:%M %p" %>
									-
									<%= meeting.end_date.strftime "%I:%M %p" %></div>
								<div class="meeting-title"><%= meeting.title %></div>
								<div class="meeting-location"><%= meeting.location.description %></div>
								<a href="<%= meeting_path meeting.id %>">
									<div class="detail">Details</div>
								</a>
							</div>
							<div class="response-button">
								<%= link_to "ACCEPT", accept_meeting_path(meeting_id: meeting.id, user_id: @user.id), class: "single-response-button light-grey-container colored-container" %>
								<%= link_to "DECLINE", decline_meeting_path(meeting_id: meeting.id, user_id: @user.id), class: "single-response-button light-grey-container colored-container" %>
								<div class="single-response-button light-grey-container colored-container"> RESCHEDULE</div>
							</div>
						</div>
					<% else %>
						<% if first %>
							<% first = false %>
						<% else %>
							</div>
						<% end %>
						<div class="date-separator rounded-box" id="<%= item.strftime '%Y%m%d' %>-i-separator" onclick="toggle('<%= item.strftime "%Y%m%d" %>-i')">
							<div><%= item.strftime "%a %d %b %Y" %></div>
						</div>
						<div id="<%= item.strftime '%Y%m%d' %>-i-accordion" class="date-accordion">
							<script type="text/javascript">
				  $(window).on('load', function () {
					  setMaxHeight("<%= item.strftime '%Y%m%d' %>-i")
				  })
							</script>
					<% end %>
				<% end %>
				</div>

		<% end %>
		<% if @undoable_breaks.count > 0 %>
			<% first = true %>

			<h2>
				UNDOABLE BREAKS
			</h2>
			<div>
				<% @undoable_breaks.each do |item| %>
					<% if item.is_a? ComputedBreak %>
						<% br = item.break %>
						<div class="break list-of-default-location rounded-box">
							<div class="default-location-name"><%= br.name %></div>
							<div class="default-location-location"><%= br.get_description %></div>
						</div>
					<% else %>
						<% if first %>
							<% first = false %>
						<% else %>
							</div>
						<% end %>
						<div class="date-separator rounded-box" id="<%= item.strftime '%Y%m%d' %>-b-separator" onclick="toggle('<%= item.strftime "%Y%m%d" %>-b')">
							<div><%= item.strftime "%a %d %b %Y" %></div>
						</div>
						<div id="<%= item.strftime '%Y%m%d' %>-b-accordion" class="date-accordion">
							<script type="text/javascript">
				  $(window).on('load', function () {
					  setMaxHeight("<%= item.strftime '%Y%m%d' %>-b")
				  })
							</script>
					<% end %>
				<% end %>
				</div>

		<% end %>
		</section>
		</div>
		<%= render 'shared/footer' %>

		<script>
		$('.warning-container').click(function (event) {
			var clicked_div = $(this);
			var new_path = "/notification/resolve_warning/" + clicked_div.attr('id');
			document.location.href = new_path;
		});

		$(window).on('load', function () {
			toggleAll()
		})
		</script>

Travlendar/app/views/notification/resolve_warning.html.erb
<%= render 'shared/header', selected: 'notifications' %>
<div id="content">
	<script type="text/javascript"></script>
	<%= render 'shared/calendar_sidebar' %>
	<section class="mainContent">

		<%= render 'shared/title_back_action', title: 'Resolve Warning', path: notification_index_path %>

		<div>
			<% @meeting_participations.each do |item| %>
					<% meeting = item.meeting %>
					<div class="meeting-invitation">
						<div class="meeting rounded-box">
							<div class="meeting-date">
								<%= meeting.start_date %>:
								<%= meeting.start_date.strftime "%I:%M %p" %>
								-
								<%= meeting.end_date.strftime "%I:%M %p" %></div>
							<div class="meeting-title"><%= meeting.title %></div>
							<div class="meeting-location"><%= meeting.location.description %></div>
							<a href="<%= meeting_path meeting.id %>">
								<div class="detail">Details</div>
							</a>
						</div>
						<div class="response-button">
							<%= link_to "ACCEPT", accept_meeting_path(meeting_id: meeting.id, user_id: @user.id), class: "single-response-button light-grey-container colored-container" %>
							<%= link_to "DECLINE", decline_meeting_path(meeting_id: meeting.id, user_id: @user.id), class: "single-response-button light-grey-container colored-container" %>
							<div class="single-response-button light-grey-container colored-container"> RESCHEDULE</div>
						</div>
					</div>
			<% end %>
			</div>
			</section>
			</div>
			<%= render 'shared/footer' %>