Travlendar/config/routes.rb
Rails.application.routes.draw do

	resources :user
	resources :meeting
	resources :notification, only: [:index]
	resources :default_location


	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get '/' => 'homepage#index', as: 'homepage'
	post '/' => 'homepage#post_index', as: 'root_post'
	post '/user/new', to: 'user#create'
	delete '/logout', to: 'homepage#destroy'

	# User
	get 'user/new'
	post 'user/:id/edit', to: 'user#post_edit'
	get 'user/search/:id' => 'user#search', as: 'search_user'
	get 'user/search_contacts/:id' => 'user#search_contacts', as: 'search_user_contact'
	get 'user/contacts/:id' => 'user#contacts', as: 'contacts_page'
	get 'user/remove_from_contacts/:user_id/:to_delete_id' => 'user#delete_contact', as: 'delete_contact'
	get 'user/add_to_contacts/:user_id/:to_add_id' => 'user#add_contact', as: 'add_contact'
	get 'user/:id/settings' => 'user#settings', as: 'settings_page'
	patch 'user/:id/settings/change_preference_list' => 'user#change_preference_list', as: 'change_preference_list'
	get 'user/:id/add_constraint' => 'user#add_constraint', as: 'add_constraint'
	post 'user/:id/add_constraint', to: 'user#create_constraint'
	get 'user/delete_constraint/:user_id/:constraint_id' => 'user#delate_constraint', as: 'delete_constraint'
	get 'user/delete_email/:user_id/:email_id' => 'user#delete_email', as: 'delete_email'
	get 'user/delete_social/:user_id/:social_user_id' => 'user#delete_social', as: 'delete_social'

	# Meeting
	get 'meeting/:id/participants_page' => 'meeting#participants_page', as: 'participants_page'
	get 'meeting/remove_participant/:meeting_id/:user_id' => 'meeting#remove_from_meeting', as: 'remove_from_meeting'
	get 'meeting/nominate_admin/:meeting_id/:user_id' => 'meeting#nominate_admin', as: 'nominate_admin'
	post '/meeting/new', to: 'meeting#create'
	get 'meeting/accept_participation/:meeting_id/:user_id' => 'meeting#accept', as: 'accept_meeting'
	get 'meeting/decline_participation/:meeting_id/:user_id' => 'meeting#decline', as: 'decline_meeting'

	# Calendar Page
	get 'calendar/day/:year/:month/:day' => 'calendar#show_day', constraints: {year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/}, as: 'calendar_day', defaults: {year: DateTime.now.year, month: DateTime.now.month, day: DateTime.now.day}
	get 'calendar/week/:year/:week' => 'calendar#show_week', constraints: {year: /\d{4}/, week: /\d{1,2}/}, as: 'calendar_week'
	get 'calendar/month/:year/:month' => 'calendar#show_month', constraints: {year: /\d{4}/, month: /\d{1,2}/}, as: 'calendar_month'

	# Travel
	get 'travel/:id' => 'travel#show', as: 'show_travel'

	# Notification
	get 'notification/resolve_warning/:meeting_participation_id' => 'notification#resolve_warning', as: 'resolve_warning'

	# Default Location
	post 'default_location/new', to: 'default_location#create'
	get 'default_location/delete_dl/:default_location_id/:user_id' => 'default_location#delete', as: 'delete_default_location'
	get 'default_location/first_def_location/:user_id' => 'default_location#first_def_location', as: 'create_first_def_location'
	post 'default_location/first_def_location/:user_id', to: 'default_location#first_creation'

	# Break
	get 'break/:id/add_break' => 'break#add_break', as: 'add_break'
	post 'break/:id/add_break', to: 'break#create_break'
	get 'user/delete_break/:user_id/:break_id' => 'break#delete_break', as: 'delete_break'
end

Travlendar/app/models/user.rb
# This class manages the model(relations, validations and base methods) of the User object
class User < ApplicationRecord
	has_many :group_users
	has_many :groups, through: :group_users
	has_many :social_users
	has_many :socials, through: :social_users
	has_many :emails
	has_many :breaks
	has_many :computed_breaks
	has_many :statuses

	has_and_belongs_to_many :contacts, class_name: 'User',
													join_table: 'contacts',
													foreign_key: 'from_user',
													association_foreign_key: 'to_user'

	has_many :default_locations
	has_many :meeting_participations
	has_many :constraints

	# This method returns the primary email of the user
	def primary_email
		Email.find(primary_email_id)
	end

	# Returns the hash digest of the given string.
	def self.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
							 BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	has_secure_password :validations => {:on => :create}
	validates :password, presence: true, :on => :create
	#validates :password_confirmation, presence: true, :on => :create
	validates :name, :surname, :nickname, :preference_list, presence: true
	validates :nickname, :primary_email_id, uniqueness: true

	validate :primary_email_in_emails
	validate :phone_number_consistency
	validate :at_least_one_travel_mean

	# This method returns the last default location before a given date
	def get_last_default_location_before(current_day)
		list_default_location = []
		default_locations.each do |dl|
			if dl.day_of_the_week < current_day.wday || ((dl.day_of_the_week == current_day.wday) && (dl.starting_hour <= (current_day.hour * 60 + current_day.min)))
				list_default_location.push dl
			end
		end
		list_default_location = list_default_location.sort_by {|dl1| [(dl1.day_of_the_week * 60 * 24 + dl1.starting_hour)]}

		if list_default_location.blank?
			get_last_default_location_before(DateTime.parse('December 9th 2017 11:59:59 PM')) # to take the last default location of the week, infinite loop if user doesn't have any def location
		else
			list_default_location.last
		end
	end

	# This method returns the first default location after a given date
	def get_first_location_after(current_day)
		list_default_location = []
		default_locations.each do |dl|
			if dl.day_of_the_week > current_day.wday || (dl.day_of_the_week == current_day.wday && dl.starting_hour >= (current_day.hour * 60 + current_day.min))
				list_default_location.push dl
			end
		end
		list_default_location = list_default_location.sort_by {|dl1| [(dl1.day_of_the_week * 60 * 24 + dl1.starting_hour)]}

		if list_default_location.blank?
			get_first_location_after(DateTime.parse('December 10th 2017 00:00:00 AM')) # to take the first default location of the week, infinite loop if user doesn't have any def location
		else
			list_default_location.first
		end
	end

	private

	# This method checks if the user always has at least one travel mean available
	def at_least_one_travel_mean
		unless preference_list.length > 0
			errors.add(:preference_list, 'can not be empty')
		end
	end

	# This method checks if the phone number inserted is valid
	def phone_number_consistency
		if phone_number
			is_number = /^[0-9]+$/
			unless is_number.match?(phone_number)
				errors.add(:phone_number, 'is not valid!')
			end
		end
	end

	# This method checks if the primary email is present
	def primary_email_in_emails
		nil if primary_email_id.blank?
	end
end

Travlendar/app/views/user/add_constraint.html.erb
<%= render 'shared/header', selected: 'settings' %>
<div id="content">
	<script type="text/javascript"></script>
	<%= render 'shared/calendar_sidebar' %>
	<section class="mainContent">

		<%= render 'shared/title_back_action', title: 'Create Constraint', path: @back_path %>

		<div id="emailPasswordContainer">

			<%= form_with scope: :constraint, local: true do |form| %>
				<p>
					I don't want to

					<%= form.select(:travel_mean) do %>
						<% [['Walk', 0], ['Drive', 1], ['use the Public Transportation', 2], ['go by Bike', 3]].each do |tm| -%>
							<%= content_tag(:option, tm.first, value: tm.last) %>
						<% end %>
					<% end %>
				</p>
				<p>
					if
					<%= form.select(:subject, [["Distance", 1], ["Duration", 2], ["Start time", 3], ["End time", 4]], {}, {id: 'subject-content', onchange: 'subjectSelected();'}) %>
					is
					<%= form.select(:operator) do %>
					<% end %>
					then

					<%= form.select(:value) do %>
					<% end %>

				</p>
				<div id="buttonsContainer">
					<%= form.submit 'Create Constraint', class: 'monoConfirmationButton' %>
				</div>

			<% end %>
		</div>

	</section>
</div>
<%= render 'shared/footer' %>


<script>
	var operators = [];
	<% @operators.each do |operator| %>
	operators.push(['<%= operator.subject_id %>', '<%=operator.description %>']);
	<% end %>
	var values = [];
	<% @values.each do |value| %>
	values.push(['<%= value.subject_id %>', '<%=value.value %>']);
	<% end %>

	function subjectSelected() {
		subject_id = $("select[name='constraint[subject]']").val();
		console.log(subject_id);

		var $inputOperator = $("select[name='constraint[operator]']");
		$inputOperator.empty();
		operators.forEach(function (operator) {
			if (operator[0] == subject_id) {
				$inputOperator.append($("<option>", {value: operator[1], html: operator[1]}));
			}
		});

		var $inputValue = $("select[name='constraint[value]']");
		$inputValue.empty();
		values.forEach(function (value) {
			if (value[0] == subject_id) {
				$inputValue.append($("<option>", {value: value[1], html: value[1]}));
			}
		});
	}

	$(function () {
		subjectSelected();
	});
</script>

Travlendar/app/views/user/contacts.html.erb
<%= render 'shared/header', selected: 'profile' %>
<div id="content">
	<script type="text/javascript"></script>
	<%= render 'shared/calendar_sidebar' %>
	<section class="mainContent">
		<%= render 'shared/title_back_action', title: 'Contacts', path: @user %>

		<div>
			<% @contacts.each do |contact| %>
				<div class="colored-container light-blue-container participant-container">
					<%= contact.name + " " + contact.surname + " (" + contact.nickname + ")" %>
					<%= link_to user_path(id: contact.id) do %>
						<div class='right-buttons colored-container light-grey-container'>
							View Profile
						</div>
					<% end %>
					<%= link_to delete_contact_path(user_id: @user.id, to_delete_id: contact.id) do %>
						<div class='right-buttons colored-container light-grey-container only-admin'>
							Remove
						</div>
					<% end %>
				</div>
			<% end %>
		</div>

		<h2 class="subtitle-contacts">
			Search Users
		</h2>

		<input id="select_origin" placeholder="Search User"/>

		<div id="invited_user_content2">
		</div>
	</section>
</div>
<%= render 'shared/footer' %>

<script type="text/javascript">
	$(function () {
		var my_id = <%= @user.id %>
			$('#select_origin').autocomplete({
				minLength: 2,
				source: '<%= search_user_contact_path(:json) %>',
				focus: function (event, ui) {
					$('#select_origin').val(ui.item.name + " " + ui.item.surname);
					return false;
				},
				// Once a value in the drop down list is selected, do the following:
				select: function (event, ui) {

					var $div_to_add = $("<div class='colored-container light-blue-container participant-container'>" +
						ui.item.name + " " + ui.item.surname + " (" + ui.item.nickname + ")" +
						"<a href=\'/user/" + ui.item.id + "\'>" +
						"<div class=\'right-buttons colored-container light-grey-container\'>" +
						"View Profile" +
						"</div>" +
						"</a><a href=\'/user/add_to_contacts/" + my_id + "/" + ui.item.id + "\'>" +
						"<div class=\'right-buttons colored-container light-grey-container only-admin\'>" +
						"Add" +
						"</div>" +
						"</a></div>");


					$('#invited_user_content2').append($div_to_add);
					return false;
				}
			})
			// The below code is straight from the jQuery example. It formats what data is displayed in the dropdown box, and can be customized.
				.data("ui-autocomplete")._renderItem = function (ul, item) {
				return $("<li></li>")
					.data("item.autocomplete", item)
					// For now which just want to show the person.given_name in the list.
					.append("<a>" + item.name + " " + item.surname + "</a>")
					.appendTo(ul);
			};
	});

</script>
<script>
	function deleteParticipant(participant) {
		var labelClicked = participant.getAttribute("data-user-id");
		var idToHide = '#Participant' + labelClicked;
		$(idToHide).toggle();
		var old_choiches = $('#link_origin_id').val();
		var toReplace = " " + labelClicked;
		old_choiches = old_choiches.replace(toReplace, "");
		$('#link_origin_id').val(old_choiches);
	}
</script>

Travlendar/app/views/user/edit.html.erb
<%= render 'shared/header', selected: 'Profile' %>
<div id="content">
	<script type="text/javascript"></script>
	<%= render 'shared/calendar_sidebar' %>
	<section class="mainContent">

		<%= render 'shared/title_back_action', title: 'Edit User', path: @user %>

		<div id="emailPasswordContainer">

			<%= form_with scope: :user, local: true do |form| %>


				<%= form.label :name, class: 'label' %>
				<%= form.text_field :name, id: 'name', type: 'text', value: @user.name %>
				<%= form.label :surname, class: 'label' %>
				<%= form.text_field :surname, id: 'surname', type: 'text', value: @user.surname %>
				<%= form.label :nickname, class: 'label' %>
				<%= form.text_field :nickname, id: 'nickname', type: 'text', value: @user.nickname %>
				<%= form.label :phone_number, class: 'label' %>
				<%= form.text_field :phone_number, id: 'phone_number', type: 'text', value: @user.phone_number %>
				<%= form.label :website, class: 'label' %>
				<%= form.text_field :website, id: 'website', type: 'text', value: @user.website %>
				<%= form.label :company, class: 'label' %>
				<%= form.text_field :company, id: 'company', type: 'text', value: @user.company %>
				<%= form.label :brief, class: 'label' %>
				<%= form.text_area :brief, id: 'brief', type: 'text', value: @user.brief %>

				<div id="buttonsContainer">
					<%= form.submit 'Edit User', class: 'monoConfirmationButton' %>
				</div>

			<% end %>

			<div id="preference-list-container">
				<div class="title-add-container ">
					Emails
					<%= image_tag("add_icon.png", alt: 'add_icon', class: 'add-image', id: 'add_email_button') %>
				</div>
			</div>

			<% flash.each do |message_type, message| %>
				<div class="alert alert-<%= message_type %>"><%= message %></div>
			<% end %>

			<div class="add-email-div">
				<%= form_with scope: :email, local: true do |form| %>

					<%= form.text_field :email, id: 'name', type: 'text' %>

					<div id="buttonsContainer">
						<%= form.submit 'Create Email', class: 'monoConfirmationButton' %>
					</div>

				<% end %>
			</div>
			<div id="preference-list-container">
				<% @emails.each do |email| %>
					<div class="constraint-container colored-container light-light-grey-container">
						<%= email.email %>
						<%= link_to image_tag("cancel_icon.png", alt: "Delate", class: 'delete-image'), delete_email_path(user_id: @user.id, email_id: email.id) %>
					</div>


				<% end %>
			</div>

			<div id="preference-list-container">
				<div class="title-add-container ">
					Socials
					<%= image_tag("add_icon.png", alt: 'add_icon', class: 'add-image', id: 'add_social_button') %>
				</div>
			</div>

			<div class="add-social-div">
				<%= form_with scope: :social_user, local: true do |form| %>
					<div class='new-social-content'>
						<div id="choose-social">
							<%= form.label :social, class: 'label' %>
							<%= form.select(:social, [], {}, {class: 'social-input'}) do %>
							<% end %>

						</div>
						<div id="choose-link">
							<%= form.label :link, class: 'label' %>
							<%= form.text_field :link, id: 'link', type: 'text' %>
						</div>

					</div>
					<div id="buttonsContainer">
						<%= form.submit 'Create Social', class: 'monoConfirmationButton' %>
					</div>
				<% end %>
			</div>

			<div id="preference-list-container">
				<% @user.social_users.each do |social_user| %>
					<div class="constraint-container colored-container light-light-grey-container">
						<%= social_user.link %>
						<%= link_to image_tag("cancel_icon.png", alt: "Delate", class: 'delete-image'), delete_social_path(user_id: @user.id, social_user_id: social_user.id) %>
					</div>


				<% end %>
			</div>
		</div>

	</section>
</div>
<%= render 'shared/footer' %>

<script type="text/javascript">

	<% if !@user.valid? %>
	$(window).on('load', function () {
		<% @user.errors.each do |error, message| %>
		displayError("<%= error.to_s %>", "<%= message %>");
		<% end %>
	})
	<% end %>

	<% if !@email.valid? %>
	$(window).on('load', function () {
		<% @email.errors.each do |error, message| %>
		displayError("<%= error.to_s %>", "<%= message %>");
		<% end %>
	})
	<% end %>
</script>

<script>
	$(function () {
		$('#add_email_button').click(function () {
			$('.add-email-div').toggle();
		});
	});

	$(function () {
		$('#add_social_button').click(function () {
			$('.add-social-div').toggle();
		});
	});


	var socials = [];
	<% @socials.each do |social| %>
	socials.push(['<%= social[1][:name] %>', '<%= social[1][:social_id] %>']);
	<% end %>

	$(function () {
		var $inputOperator = $("select[name='social_user[social]']");
		$inputOperator.empty();
		socials.forEach(function (social) {
			$inputOperator.append($("<option>", {value: social[1], html: social[0]}));
		});

	});

</script>

Travlendar/app/views/user/new.html.erb
<html>

<head>
	<meta charset="utf-8">
	<title>Travlendar+: Complete Registration</title>
</head>

<body>
<div class="outer">
	<div id="mainWrapper">
		<div class="logoContainer">
			<a class="title">Complete your Registration!</a>
		</div>
		<div id="emailPasswordContainer">

			<%= form_with scope: :user, local: true do |form| %>

				<script type="text/javascript">
			<% if !@user.valid? %>
			$(window).on('load', function () {
				<% @user.errors.each do |error, message| %>
				displayError("<%= error.to_s %>", "<%= message %>")
				<% end %>
			})
			<% end %>
				</script>

				<%= form.label :email, class: 'label' %>
				<%= form.text_field :email, id: 'email', type: 'text', value: if @unregistered_user
																																				@unregistered_user.email
																																			elsif @user.emails
																																				@user.emails.first.email
																																			end %>
				<%= form.label :password, class: 'label' %>
				<%= form.text_field :password, id: 'password', type: 'password', value: if @unregistered_user
																																									@unregistered_user.password
																																								elsif @user.password
																																									@user.password
																																								end %>
				<%= form.label :password_confirmation, class: 'label' %>
				<%= form.text_field :password_confirmation, id: 'password_confirmation', type: 'password', value: if @unregistered_user
																																																						@unregistered_user.password
																																																					elsif @user.password
																																																						@user.password
																																																					end %>
				<%= form.label :name, class: 'label' %>
				<%= form.text_field :name, id: 'name', type: 'text' %>
				<%= form.label :surname, class: 'label' %>
				<%= form.text_field :surname, id: 'surname', type: 'text' %>
				<%= form.label :nickname, class: 'label' %>
				<%= form.text_field :nickname, id: 'nickname', type: 'text' %>
				<%= form.label :brief, class: 'label' %>
				<%= form.text_area :brief, id: 'brief', type: 'text' %>

				<%= form.label :preference_list, class: 'label' %>
				<%= render 'shared/preference_list', form: form %>


				<div id="buttonsContainer">
					<%= form.submit 'Save User', class: 'monoConfirmationButton' %>
				</div>

			<% end %>
		</div>


	</div>
</div>


</body>

</html>

Travlendar/app/views/user/settings.html.erb
<%= render 'shared/header', selected: 'settings' %>
<div id="content">
	<script type="text/javascript"></script>
	<%= render 'shared/calendar_sidebar' %>
	<section class="mainContent" >
		<%= render 'shared/title_back_action', title: 'Settings' %>


		<h2 class="subtitle-contacts" style="margin-top: 5px;">
			Preference List
		</h2>
		<div id="preference-list-container">
			<%= form_for @user, url: change_preference_list_path do |form| %>
				<%= render 'shared/preference_list', form: form %>
				<%= form.submit "Save" %>
			<% end %>
		</div>

		<div id="preference-list-container">
			<div class="title-add-container ">
				Constraints
				<%= link_to image_tag("add_icon.png", alt: 'add_icon', class: 'add-image'), add_constraint_path %>
			</div>
		</div>
		<div id="preference-list-container">
			<% @user.constraints.each do |constraint| %>
				<div class="constraint-container colored-container light-light-grey-container">
					<%= constraint.get_description %>
					<%= link_to image_tag("cancel_icon.png", alt: "Delate", class: 'delete-image'), delete_constraint_path(user_id: @user.id, constraint_id: constraint.id) %>
				</div>
			<% end %>
		</div>

		<div id="preference-list-container">
			<div class="title-add-container ">
				Default Locations
				<%= link_to image_tag("add_icon.png", alt: 'add_icon', class: 'add-image'), new_default_location_path %>
			</div>
		</div>

		<div id="preference-list-container">
			<% @user.default_locations.order('day_of_the_week * 60 * 24 + starting_hour').each do |dl| %>
				<div class="default-location list-of-default-location rounded-box">
					<div class="default-location-name"><%= dl.name %></div>
					<div class="default-location-location"><%= dl.location.description %></div>
					<a href='<%= default_location_path(id: dl.id) %>'>
						<div class="detail">Details</div>
					</a>
				</div>

			<% end %>
		</div>


		<div id="preference-list-container">
			<div class="title-add-container ">
				Breaks
				<%= link_to image_tag("add_icon.png", alt: 'add_icon', class: 'add-image'), add_break_path %>
			</div>
		</div>

		<div id="preference-list-container">
			<% @user.breaks.each do |br| %>
				<div class="break list-of-default-location rounded-box">
					<div class="default-location-name"><%= br.name %></div>
					<div class="default-location-location"><%= br.get_description %></div>
					<%= link_to image_tag("cancel_icon.png", alt: "Delate", class: 'delete-image delete-image-in-block'), delete_break_path(user_id: @user.id, break_id: br.id) %>

				</div>

			<% end %>
		</div>

	</section>
</div>
<%= render 'shared/footer' %>

<script>
	function openConstraintCreate() {
			$('#create-constraint').toggle();
  }
</script>

Travlendar/app/views/user/show.html.erb
<%= render 'shared/header', selected: 'profile' %>
<div id="content">
	<%= render 'shared/calendar_sidebar' %>
	<section class="mainContent">
		<!-- insierire freccia indietro se non sono me stesso alla pagina prima -->
		<%= link_to "Edit Profile", edit_user_path, class: "profile-detail detail light-light-grey-container colored-container" if @user.id == current_user.id %>
		<%= link_to "Log out", logout_path, method: :delete, class: 'profile-detail light-grey-container colored-container logout' if @user.id == current_user.id %>

		<div><%= image_tag(unless File.file? ("/public/profile_images/" + @user.primary_email.email + ".png")
												 "defaultProfileImage.png"
											 else
												 "profile_images/" + @user.nickname + ".png"
											 end, id: "roundedImages") %></div>

		<div id="name-surname">
			<%= @user.name + " " + @user.surname %>
		</div>

		<div class="nickname-container">
			(<%= @user.nickname %>)
		</div>

		<% unless @user.brief.blank? %>
			<div id="brief">
				<%= @user.brief %>
			</div>
		<% end %>

		<div class="email-container light-light-grey-container colored-container">
			<%= @user.primary_email.email %>
		</div>

		<% unless @user.phone_number.blank? %>
			<div class="email-container light-light-grey-container colored-container">
				<%= @user.phone_number %>
			</div>
		<% end %>

		<% unless @user.website.blank? %>
			<div class="email-container light-light-grey-container colored-container">
				<a href="<%= @user.website %>" target="_blank">Personal Website</a>
			</div>
		<% end %>

		<% unless @user.company.blank? %>
			<div class="email-container light-light-grey-container colored-container">
				<%= @user.company %>
			</div>
		<% end %>

		<div class="profile-page-buttons">
			<% if @user.id == current_user.id %>
				<div class="colored-container light-grey-container date-time-block">
					<%= link_to('Manage Contacts', contacts_page_path, id: @user.id) %>
				</div>
			<% elsif current_user.contacts.ids.include? @user.id %>
				<div class="colored-container light-grey-container date-time-block">
					<%= link_to('Remove from Contacts', delete_contact_path(current_user.id, @user.id)) %>
				</div>
			<% else %>
				<div class="colored-container light-grey-container date-time-block">
					<%= link_to('Add to Contacts', add_contact_path(current_user.id, @user.id)) %>
				</div>
			<% end %>
		</div>

		<div class="social-container">
			<% @user.social_users.each do |social| %>
				<div class=" social-boxes light-light-grey-container colored-container">
					<%= link_to image_tag(@socials[social.social_id][:icon_path], alt: @socials[social.social_id][:name], class: 'social-icon'), 'http://' + social.link %>
				</div>
			<% end %>
		</div>


	</section>
</div>
<%= render 'shared/footer' %>